version: 0.0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  git_access_token:
    secure: V8i7UZRY6IQFpngUi2sgnunCFZKvE4al96flaBKyWqXyRLmTabX0/1Z0Tpl8BWKr
  appveyor_api_token:
    secure: eMpCyScSyam7rRtm3bSRAzt29qATXHWxk8mfgdTpyh0=
nuget:
  account_feed: true
  disable_publish_on_pr: true
install:
- ps: scripts/set-version.ps1
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
build_script:
- dotnet build -c %CONFIGURATION%
test_script:
- dotnet test -c %CONFIGURATION%
before_package:
- ps: scripts/update-release-notes.ps1
deploy:
- provider: NuGet
  api_key: 
    secure: CKc1otCe7SBBZMtNw0PWreC0fHtdY6jhRTosT8o2CLbg1mFKeCDaH6RHgWFYs+i4
after_deploy:
- ps: scripts/set-version-tag-in-git.ps1